import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "./components/theme-provider";
import "./globals.css";
import { ErrorWrapper } from "./error-wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    //usually used to overwrite in the child component
    //absolute: "Codevolution",
    default: "Codevolution",
    template: "%s | Codevolution",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
            <p>Default Layout Header</p>
          </header>
          <ErrorWrapper>{children}</ErrorWrapper>
          <footer style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
            <p>Footer</p>
          </footer>
        </body>
      </ThemeProvider>
    </html>
  );
}
